/**
 * generated by Xtext 2.12.0
 */
package uk.ac.ox.cs.ide;

import uk.ac.ox.cs.ide.AbstractMDMLIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MDMLIdeModule extends AbstractMDMLIdeModule {
}
