/**
 * generated by Xtext 2.12.0
 */
package uk.ac.ox.cs.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import uk.ac.ox.cs.MDMLRuntimeModule;
import uk.ac.ox.cs.MDMLStandaloneSetup;
import uk.ac.ox.cs.ide.MDMLIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MDMLIdeSetup extends MDMLStandaloneSetup {
  @Override
  public Injector createInjector() {
    MDMLRuntimeModule _mDMLRuntimeModule = new MDMLRuntimeModule();
    MDMLIdeModule _mDMLIdeModule = new MDMLIdeModule();
    return Guice.createInjector(Modules2.mixin(_mDMLRuntimeModule, _mDMLIdeModule));
  }
}
