/*
 * generated by Xtext 2.12.0
 */
package uk.ac.ox.cs.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMDMLScopeProvider extends DelegatingScopeProvider {
}
