/*
 * generated by Xtext 2.12.0
 */
package uk.ac.ox.cs


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MDMLStandaloneSetup extends MDMLStandaloneSetupGenerated {

	def static void doSetup() {
		new MDMLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
