/**
 * generated by Xtext 2.12.0
 */
package uk.ac.ox.cs.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import uk.ac.ox.cs.ui.AbstractMDMLUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class MDMLUiModule extends AbstractMDMLUiModule {
  public MDMLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
