/**
 * generated by Xtext 2.12.0
 */
package uk.ac.ox.cs.mDML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Constraint</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.ox.cs.mDML.Constraint#getName <em>Name</em>}</li>
 *   <li>{@link uk.ac.ox.cs.mDML.Constraint#getSrc <em>Src</em>}</li>
 *   <li>{@link uk.ac.ox.cs.mDML.Constraint#getPred <em>Pred</em>}</li>
 *   <li>{@link uk.ac.ox.cs.mDML.Constraint#getDest <em>Dest</em>}</li>
 * </ul>
 *
 * @see uk.ac.ox.cs.mDML.MDMLPackage#getConstraint()
 * @model
 * @generated
 */
public interface Constraint extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see uk.ac.ox.cs.mDML.MDMLPackage#getConstraint_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link uk.ac.ox.cs.mDML.Constraint#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Src</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Src</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Src</em>' containment reference.
   * @see #setSrc(DataElement)
   * @see uk.ac.ox.cs.mDML.MDMLPackage#getConstraint_Src()
   * @model containment="true"
   * @generated
   */
  DataElement getSrc();

  /**
   * Sets the value of the '{@link uk.ac.ox.cs.mDML.Constraint#getSrc <em>Src</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Src</em>' containment reference.
   * @see #getSrc()
   * @generated
   */
  void setSrc(DataElement value);

  /**
   * Returns the value of the '<em><b>Pred</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pred</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pred</em>' reference.
   * @see #setPred(Predicate)
   * @see uk.ac.ox.cs.mDML.MDMLPackage#getConstraint_Pred()
   * @model
   * @generated
   */
  Predicate getPred();

  /**
   * Sets the value of the '{@link uk.ac.ox.cs.mDML.Constraint#getPred <em>Pred</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pred</em>' reference.
   * @see #getPred()
   * @generated
   */
  void setPred(Predicate value);

  /**
   * Returns the value of the '<em><b>Dest</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dest</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dest</em>' containment reference.
   * @see #setDest(DataElement)
   * @see uk.ac.ox.cs.mDML.MDMLPackage#getConstraint_Dest()
   * @model containment="true"
   * @generated
   */
  DataElement getDest();

  /**
   * Sets the value of the '{@link uk.ac.ox.cs.mDML.Constraint#getDest <em>Dest</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dest</em>' containment reference.
   * @see #getDest()
   * @generated
   */
  void setDest(DataElement value);

} // Constraint
