/**
 * generated by Xtext 2.12.0
 */
package uk.ac.ox.cs.mDML;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Class</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.ox.cs.mDML.DataClass#getStatus <em>Status</em>}</li>
 *   <li>{@link uk.ac.ox.cs.mDML.DataClass#getGuid <em>Guid</em>}</li>
 *   <li>{@link uk.ac.ox.cs.mDML.DataClass#getRefines <em>Refines</em>}</li>
 *   <li>{@link uk.ac.ox.cs.mDML.DataClass#getDataelements <em>Dataelements</em>}</li>
 *   <li>{@link uk.ac.ox.cs.mDML.DataClass#getExtension <em>Extension</em>}</li>
 * </ul>
 *
 * @see uk.ac.ox.cs.mDML.MDMLPackage#getDataClass()
 * @model
 * @generated
 */
public interface DataClass extends RelationSource, RelationDestination, ContainerElement
{
  /**
   * Returns the value of the '<em><b>Status</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Status</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Status</em>' attribute.
   * @see #setStatus(String)
   * @see uk.ac.ox.cs.mDML.MDMLPackage#getDataClass_Status()
   * @model
   * @generated
   */
  String getStatus();

  /**
   * Sets the value of the '{@link uk.ac.ox.cs.mDML.DataClass#getStatus <em>Status</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Status</em>' attribute.
   * @see #getStatus()
   * @generated
   */
  void setStatus(String value);

  /**
   * Returns the value of the '<em><b>Guid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Guid</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Guid</em>' attribute.
   * @see #setGuid(String)
   * @see uk.ac.ox.cs.mDML.MDMLPackage#getDataClass_Guid()
   * @model
   * @generated
   */
  String getGuid();

  /**
   * Sets the value of the '{@link uk.ac.ox.cs.mDML.DataClass#getGuid <em>Guid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Guid</em>' attribute.
   * @see #getGuid()
   * @generated
   */
  void setGuid(String value);

  /**
   * Returns the value of the '<em><b>Refines</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Refines</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Refines</em>' attribute.
   * @see #setRefines(String)
   * @see uk.ac.ox.cs.mDML.MDMLPackage#getDataClass_Refines()
   * @model
   * @generated
   */
  String getRefines();

  /**
   * Sets the value of the '{@link uk.ac.ox.cs.mDML.DataClass#getRefines <em>Refines</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Refines</em>' attribute.
   * @see #getRefines()
   * @generated
   */
  void setRefines(String value);

  /**
   * Returns the value of the '<em><b>Dataelements</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.ox.cs.mDML.ContainerElement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dataelements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dataelements</em>' containment reference list.
   * @see uk.ac.ox.cs.mDML.MDMLPackage#getDataClass_Dataelements()
   * @model containment="true"
   * @generated
   */
  EList<ContainerElement> getDataelements();

  /**
   * Returns the value of the '<em><b>Extension</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.ox.cs.mDML.ExtensionItem}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Extension</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Extension</em>' containment reference list.
   * @see uk.ac.ox.cs.mDML.MDMLPackage#getDataClass_Extension()
   * @model containment="true"
   * @generated
   */
  EList<ExtensionItem> getExtension();

} // DataClass
