/**
 * generated by Xtext 2.12.0
 */
package uk.ac.ox.cs.mDML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.ox.cs.mDML.DataType#getStatus <em>Status</em>}</li>
 *   <li>{@link uk.ac.ox.cs.mDML.DataType#getGuid <em>Guid</em>}</li>
 *   <li>{@link uk.ac.ox.cs.mDML.DataType#getRefines <em>Refines</em>}</li>
 *   <li>{@link uk.ac.ox.cs.mDML.DataType#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see uk.ac.ox.cs.mDML.MDMLPackage#getDataType()
 * @model
 * @generated
 */
public interface DataType extends RelationSource, RelationDestination
{
  /**
   * Returns the value of the '<em><b>Status</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Status</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Status</em>' attribute.
   * @see #setStatus(String)
   * @see uk.ac.ox.cs.mDML.MDMLPackage#getDataType_Status()
   * @model
   * @generated
   */
  String getStatus();

  /**
   * Sets the value of the '{@link uk.ac.ox.cs.mDML.DataType#getStatus <em>Status</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Status</em>' attribute.
   * @see #getStatus()
   * @generated
   */
  void setStatus(String value);

  /**
   * Returns the value of the '<em><b>Guid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Guid</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Guid</em>' attribute.
   * @see #setGuid(String)
   * @see uk.ac.ox.cs.mDML.MDMLPackage#getDataType_Guid()
   * @model
   * @generated
   */
  String getGuid();

  /**
   * Sets the value of the '{@link uk.ac.ox.cs.mDML.DataType#getGuid <em>Guid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Guid</em>' attribute.
   * @see #getGuid()
   * @generated
   */
  void setGuid(String value);

  /**
   * Returns the value of the '<em><b>Refines</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Refines</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Refines</em>' attribute.
   * @see #setRefines(String)
   * @see uk.ac.ox.cs.mDML.MDMLPackage#getDataType_Refines()
   * @model
   * @generated
   */
  String getRefines();

  /**
   * Sets the value of the '{@link uk.ac.ox.cs.mDML.DataType#getRefines <em>Refines</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Refines</em>' attribute.
   * @see #getRefines()
   * @generated
   */
  void setRefines(String value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see uk.ac.ox.cs.mDML.MDMLPackage#getDataType_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link uk.ac.ox.cs.mDML.DataType#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // DataType
