/**
 * generated by Xtext 2.12.0
 */
package uk.ac.ox.cs.mDML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.ox.cs.mDML.DataElement#getStatus <em>Status</em>}</li>
 *   <li>{@link uk.ac.ox.cs.mDML.DataElement#getGuid <em>Guid</em>}</li>
 *   <li>{@link uk.ac.ox.cs.mDML.DataElement#getRefines <em>Refines</em>}</li>
 *   <li>{@link uk.ac.ox.cs.mDML.DataElement#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see uk.ac.ox.cs.mDML.MDMLPackage#getDataElement()
 * @model
 * @generated
 */
public interface DataElement extends RelationSource, RelationDestination, ContainerElement
{
  /**
   * Returns the value of the '<em><b>Status</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Status</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Status</em>' attribute.
   * @see #setStatus(String)
   * @see uk.ac.ox.cs.mDML.MDMLPackage#getDataElement_Status()
   * @model
   * @generated
   */
  String getStatus();

  /**
   * Sets the value of the '{@link uk.ac.ox.cs.mDML.DataElement#getStatus <em>Status</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Status</em>' attribute.
   * @see #getStatus()
   * @generated
   */
  void setStatus(String value);

  /**
   * Returns the value of the '<em><b>Guid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Guid</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Guid</em>' attribute.
   * @see #setGuid(String)
   * @see uk.ac.ox.cs.mDML.MDMLPackage#getDataElement_Guid()
   * @model
   * @generated
   */
  String getGuid();

  /**
   * Sets the value of the '{@link uk.ac.ox.cs.mDML.DataElement#getGuid <em>Guid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Guid</em>' attribute.
   * @see #getGuid()
   * @generated
   */
  void setGuid(String value);

  /**
   * Returns the value of the '<em><b>Refines</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Refines</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Refines</em>' attribute.
   * @see #setRefines(String)
   * @see uk.ac.ox.cs.mDML.MDMLPackage#getDataElement_Refines()
   * @model
   * @generated
   */
  String getRefines();

  /**
   * Sets the value of the '{@link uk.ac.ox.cs.mDML.DataElement#getRefines <em>Refines</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Refines</em>' attribute.
   * @see #getRefines()
   * @generated
   */
  void setRefines(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(DataType)
   * @see uk.ac.ox.cs.mDML.MDMLPackage#getDataElement_Type()
   * @model
   * @generated
   */
  DataType getType();

  /**
   * Sets the value of the '{@link uk.ac.ox.cs.mDML.DataElement#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(DataType value);

} // DataElement
