/**
 * generated by Xtext 2.12.0
 */
package uk.ac.ox.cs.mDML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Enumerated Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.ox.cs.mDML.EnumeratedType#getType <em>Type</em>}</li>
 *   <li>{@link uk.ac.ox.cs.mDML.EnumeratedType#isArray <em>Array</em>}</li>
 *   <li>{@link uk.ac.ox.cs.mDML.EnumeratedType#getLength <em>Length</em>}</li>
 * </ul>
 *
 * @see uk.ac.ox.cs.mDML.MDMLPackage#getEnumeratedType()
 * @model
 * @generated
 */
public interface EnumeratedType extends DataType
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(PrimitiveType)
   * @see uk.ac.ox.cs.mDML.MDMLPackage#getEnumeratedType_Type()
   * @model containment="true"
   * @generated
   */
  PrimitiveType getType();

  /**
   * Sets the value of the '{@link uk.ac.ox.cs.mDML.EnumeratedType#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(PrimitiveType value);

  /**
   * Returns the value of the '<em><b>Array</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Array</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Array</em>' attribute.
   * @see #setArray(boolean)
   * @see uk.ac.ox.cs.mDML.MDMLPackage#getEnumeratedType_Array()
   * @model
   * @generated
   */
  boolean isArray();

  /**
   * Sets the value of the '{@link uk.ac.ox.cs.mDML.EnumeratedType#isArray <em>Array</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Array</em>' attribute.
   * @see #isArray()
   * @generated
   */
  void setArray(boolean value);

  /**
   * Returns the value of the '<em><b>Length</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Length</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Length</em>' attribute.
   * @see #setLength(int)
   * @see uk.ac.ox.cs.mDML.MDMLPackage#getEnumeratedType_Length()
   * @model
   * @generated
   */
  int getLength();

  /**
   * Sets the value of the '{@link uk.ac.ox.cs.mDML.EnumeratedType#getLength <em>Length</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Length</em>' attribute.
   * @see #getLength()
   * @generated
   */
  void setLength(int value);

} // EnumeratedType
