/**
 * generated by Xtext 2.12.0
 */
package uk.ac.ox.cs.mDML;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see uk.ac.ox.cs.mDML.MDMLFactory
 * @model kind="package"
 * @generated
 */
public interface MDMLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "mDML";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ac.uk/ox/cs/MDML";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "mDML";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MDMLPackage eINSTANCE = uk.ac.ox.cs.mDML.impl.MDMLPackageImpl.init();

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.mDML.impl.DomainRegistryImpl <em>Domain Registry</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.mDML.impl.DomainRegistryImpl
   * @see uk.ac.ox.cs.mDML.impl.MDMLPackageImpl#getDomainRegistry()
   * @generated
   */
  int DOMAIN_REGISTRY = 0;

  /**
   * The feature id for the '<em><b>Registered Items</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAIN_REGISTRY__REGISTERED_ITEMS = 0;

  /**
   * The number of structural features of the '<em>Domain Registry</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAIN_REGISTRY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.mDML.impl.RelationSourceImpl <em>Relation Source</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.mDML.impl.RelationSourceImpl
   * @see uk.ac.ox.cs.mDML.impl.MDMLPackageImpl#getRelationSource()
   * @generated
   */
  int RELATION_SOURCE = 4;

  /**
   * The number of structural features of the '<em>Relation Source</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION_SOURCE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.mDML.impl.DataModelImpl <em>Data Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.mDML.impl.DataModelImpl
   * @see uk.ac.ox.cs.mDML.impl.MDMLPackageImpl#getDataModel()
   * @generated
   */
  int DATA_MODEL = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_MODEL__NAME = RELATION_SOURCE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Status</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_MODEL__STATUS = RELATION_SOURCE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Guid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_MODEL__GUID = RELATION_SOURCE_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Refines</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_MODEL__REFINES = RELATION_SOURCE_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_MODEL__ELEMENTS = RELATION_SOURCE_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Relations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_MODEL__RELATIONS = RELATION_SOURCE_FEATURE_COUNT + 5;

  /**
   * The feature id for the '<em><b>Constraint</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_MODEL__CONSTRAINT = RELATION_SOURCE_FEATURE_COUNT + 6;

  /**
   * The feature id for the '<em><b>Predicate</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_MODEL__PREDICATE = RELATION_SOURCE_FEATURE_COUNT + 7;

  /**
   * The number of structural features of the '<em>Data Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_MODEL_FEATURE_COUNT = RELATION_SOURCE_FEATURE_COUNT + 8;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.mDML.impl.DataItemImpl <em>Data Item</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.mDML.impl.DataItemImpl
   * @see uk.ac.ox.cs.mDML.impl.MDMLPackageImpl#getDataItem()
   * @generated
   */
  int DATA_ITEM = 2;

  /**
   * The feature id for the '<em><b>Dataitem</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_ITEM__DATAITEM = 0;

  /**
   * The number of structural features of the '<em>Data Item</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_ITEM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.mDML.impl.ContainerElementImpl <em>Container Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.mDML.impl.ContainerElementImpl
   * @see uk.ac.ox.cs.mDML.impl.MDMLPackageImpl#getContainerElement()
   * @generated
   */
  int CONTAINER_ELEMENT = 14;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINER_ELEMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Container Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINER_ELEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.mDML.impl.ReferenceImpl <em>Reference</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.mDML.impl.ReferenceImpl
   * @see uk.ac.ox.cs.mDML.impl.MDMLPackageImpl#getReference()
   * @generated
   */
  int REFERENCE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE__NAME = CONTAINER_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE__TYPE = CONTAINER_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Reference</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE_FEATURE_COUNT = CONTAINER_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.mDML.impl.RelationDestinationImpl <em>Relation Destination</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.mDML.impl.RelationDestinationImpl
   * @see uk.ac.ox.cs.mDML.impl.MDMLPackageImpl#getRelationDestination()
   * @generated
   */
  int RELATION_DESTINATION = 5;

  /**
   * The number of structural features of the '<em>Relation Destination</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION_DESTINATION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.mDML.impl.RelationshipImpl <em>Relationship</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.mDML.impl.RelationshipImpl
   * @see uk.ac.ox.cs.mDML.impl.MDMLPackageImpl#getRelationship()
   * @generated
   */
  int RELATIONSHIP = 6;

  /**
   * The feature id for the '<em><b>Src</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONSHIP__SRC = 0;

  /**
   * The feature id for the '<em><b>Dest</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONSHIP__DEST = 1;

  /**
   * The number of structural features of the '<em>Relationship</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONSHIP_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.mDML.impl.ExtensionItemImpl <em>Extension Item</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.mDML.impl.ExtensionItemImpl
   * @see uk.ac.ox.cs.mDML.impl.MDMLPackageImpl#getExtensionItem()
   * @generated
   */
  int EXTENSION_ITEM = 7;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTENSION_ITEM__KEY = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTENSION_ITEM__VALUE = 1;

  /**
   * The number of structural features of the '<em>Extension Item</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTENSION_ITEM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.mDML.impl.ImportImpl <em>Import</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.mDML.impl.ImportImpl
   * @see uk.ac.ox.cs.mDML.impl.MDMLPackageImpl#getImport()
   * @generated
   */
  int IMPORT = 8;

  /**
   * The feature id for the '<em><b>Imported Namespace</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT__IMPORTED_NAMESPACE = 0;

  /**
   * The number of structural features of the '<em>Import</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.mDML.impl.DataTypeImpl <em>Data Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.mDML.impl.DataTypeImpl
   * @see uk.ac.ox.cs.mDML.impl.MDMLPackageImpl#getDataType()
   * @generated
   */
  int DATA_TYPE = 9;

  /**
   * The feature id for the '<em><b>Status</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_TYPE__STATUS = RELATION_SOURCE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Guid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_TYPE__GUID = RELATION_SOURCE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Refines</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_TYPE__REFINES = RELATION_SOURCE_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_TYPE__NAME = RELATION_SOURCE_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Data Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_TYPE_FEATURE_COUNT = RELATION_SOURCE_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.mDML.impl.EnumeratedTypeImpl <em>Enumerated Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.mDML.impl.EnumeratedTypeImpl
   * @see uk.ac.ox.cs.mDML.impl.MDMLPackageImpl#getEnumeratedType()
   * @generated
   */
  int ENUMERATED_TYPE = 10;

  /**
   * The feature id for the '<em><b>Status</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUMERATED_TYPE__STATUS = DATA_TYPE__STATUS;

  /**
   * The feature id for the '<em><b>Guid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUMERATED_TYPE__GUID = DATA_TYPE__GUID;

  /**
   * The feature id for the '<em><b>Refines</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUMERATED_TYPE__REFINES = DATA_TYPE__REFINES;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUMERATED_TYPE__NAME = DATA_TYPE__NAME;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUMERATED_TYPE__TYPE = DATA_TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Array</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUMERATED_TYPE__ARRAY = DATA_TYPE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Length</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUMERATED_TYPE__LENGTH = DATA_TYPE_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Enumerated Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUMERATED_TYPE_FEATURE_COUNT = DATA_TYPE_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.mDML.impl.ReferenceTypeImpl <em>Reference Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.mDML.impl.ReferenceTypeImpl
   * @see uk.ac.ox.cs.mDML.impl.MDMLPackageImpl#getReferenceType()
   * @generated
   */
  int REFERENCE_TYPE = 11;

  /**
   * The feature id for the '<em><b>Status</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE_TYPE__STATUS = DATA_TYPE__STATUS;

  /**
   * The feature id for the '<em><b>Guid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE_TYPE__GUID = DATA_TYPE__GUID;

  /**
   * The feature id for the '<em><b>Refines</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE_TYPE__REFINES = DATA_TYPE__REFINES;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE_TYPE__NAME = DATA_TYPE__NAME;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE_TYPE__TYPE = DATA_TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Reference Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE_TYPE_FEATURE_COUNT = DATA_TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.mDML.impl.PrimitiveTypeImpl <em>Primitive Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.mDML.impl.PrimitiveTypeImpl
   * @see uk.ac.ox.cs.mDML.impl.MDMLPackageImpl#getPrimitiveType()
   * @generated
   */
  int PRIMITIVE_TYPE = 12;

  /**
   * The feature id for the '<em><b>Status</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMITIVE_TYPE__STATUS = DATA_TYPE__STATUS;

  /**
   * The feature id for the '<em><b>Guid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMITIVE_TYPE__GUID = DATA_TYPE__GUID;

  /**
   * The feature id for the '<em><b>Refines</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMITIVE_TYPE__REFINES = DATA_TYPE__REFINES;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMITIVE_TYPE__NAME = DATA_TYPE__NAME;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMITIVE_TYPE__TYPE = DATA_TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Rule</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMITIVE_TYPE__RULE = DATA_TYPE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Primitive Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMITIVE_TYPE_FEATURE_COUNT = DATA_TYPE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.mDML.impl.BasicImpl <em>Basic</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.mDML.impl.BasicImpl
   * @see uk.ac.ox.cs.mDML.impl.MDMLPackageImpl#getBasic()
   * @generated
   */
  int BASIC = 13;

  /**
   * The feature id for the '<em><b>Typename</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BASIC__TYPENAME = 0;

  /**
   * The number of structural features of the '<em>Basic</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BASIC_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.mDML.impl.DataClassImpl <em>Data Class</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.mDML.impl.DataClassImpl
   * @see uk.ac.ox.cs.mDML.impl.MDMLPackageImpl#getDataClass()
   * @generated
   */
  int DATA_CLASS = 15;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_CLASS__NAME = RELATION_SOURCE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Status</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_CLASS__STATUS = RELATION_SOURCE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Guid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_CLASS__GUID = RELATION_SOURCE_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Refines</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_CLASS__REFINES = RELATION_SOURCE_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Dataelements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_CLASS__DATAELEMENTS = RELATION_SOURCE_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Extension</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_CLASS__EXTENSION = RELATION_SOURCE_FEATURE_COUNT + 5;

  /**
   * The number of structural features of the '<em>Data Class</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_CLASS_FEATURE_COUNT = RELATION_SOURCE_FEATURE_COUNT + 6;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.mDML.impl.DataElementImpl <em>Data Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.mDML.impl.DataElementImpl
   * @see uk.ac.ox.cs.mDML.impl.MDMLPackageImpl#getDataElement()
   * @generated
   */
  int DATA_ELEMENT = 16;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_ELEMENT__NAME = RELATION_SOURCE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Status</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_ELEMENT__STATUS = RELATION_SOURCE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Guid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_ELEMENT__GUID = RELATION_SOURCE_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Refines</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_ELEMENT__REFINES = RELATION_SOURCE_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_ELEMENT__TYPE = RELATION_SOURCE_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Data Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_ELEMENT_FEATURE_COUNT = RELATION_SOURCE_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.mDML.impl.ConstraintImpl <em>Constraint</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.mDML.impl.ConstraintImpl
   * @see uk.ac.ox.cs.mDML.impl.MDMLPackageImpl#getConstraint()
   * @generated
   */
  int CONSTRAINT = 17;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRAINT__NAME = 0;

  /**
   * The feature id for the '<em><b>Src</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRAINT__SRC = 1;

  /**
   * The feature id for the '<em><b>Pred</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRAINT__PRED = 2;

  /**
   * The feature id for the '<em><b>Dest</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRAINT__DEST = 3;

  /**
   * The number of structural features of the '<em>Constraint</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRAINT_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link uk.ac.ox.cs.mDML.impl.PredicateImpl <em>Predicate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.ox.cs.mDML.impl.PredicateImpl
   * @see uk.ac.ox.cs.mDML.impl.MDMLPackageImpl#getPredicate()
   * @generated
   */
  int PREDICATE = 18;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE__NAME = 0;

  /**
   * The feature id for the '<em><b>Predicate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE__PREDICATE = 1;

  /**
   * The number of structural features of the '<em>Predicate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.mDML.DomainRegistry <em>Domain Registry</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Domain Registry</em>'.
   * @see uk.ac.ox.cs.mDML.DomainRegistry
   * @generated
   */
  EClass getDomainRegistry();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.ox.cs.mDML.DomainRegistry#getRegisteredItems <em>Registered Items</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Registered Items</em>'.
   * @see uk.ac.ox.cs.mDML.DomainRegistry#getRegisteredItems()
   * @see #getDomainRegistry()
   * @generated
   */
  EReference getDomainRegistry_RegisteredItems();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.mDML.DataModel <em>Data Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Data Model</em>'.
   * @see uk.ac.ox.cs.mDML.DataModel
   * @generated
   */
  EClass getDataModel();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.ox.cs.mDML.DataModel#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.ox.cs.mDML.DataModel#getName()
   * @see #getDataModel()
   * @generated
   */
  EAttribute getDataModel_Name();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.ox.cs.mDML.DataModel#getStatus <em>Status</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Status</em>'.
   * @see uk.ac.ox.cs.mDML.DataModel#getStatus()
   * @see #getDataModel()
   * @generated
   */
  EAttribute getDataModel_Status();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.ox.cs.mDML.DataModel#getGuid <em>Guid</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Guid</em>'.
   * @see uk.ac.ox.cs.mDML.DataModel#getGuid()
   * @see #getDataModel()
   * @generated
   */
  EAttribute getDataModel_Guid();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.ox.cs.mDML.DataModel#getRefines <em>Refines</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Refines</em>'.
   * @see uk.ac.ox.cs.mDML.DataModel#getRefines()
   * @see #getDataModel()
   * @generated
   */
  EAttribute getDataModel_Refines();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.ox.cs.mDML.DataModel#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see uk.ac.ox.cs.mDML.DataModel#getElements()
   * @see #getDataModel()
   * @generated
   */
  EReference getDataModel_Elements();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.ox.cs.mDML.DataModel#getRelations <em>Relations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Relations</em>'.
   * @see uk.ac.ox.cs.mDML.DataModel#getRelations()
   * @see #getDataModel()
   * @generated
   */
  EReference getDataModel_Relations();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.ox.cs.mDML.DataModel#getConstraint <em>Constraint</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Constraint</em>'.
   * @see uk.ac.ox.cs.mDML.DataModel#getConstraint()
   * @see #getDataModel()
   * @generated
   */
  EReference getDataModel_Constraint();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.ox.cs.mDML.DataModel#getPredicate <em>Predicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Predicate</em>'.
   * @see uk.ac.ox.cs.mDML.DataModel#getPredicate()
   * @see #getDataModel()
   * @generated
   */
  EReference getDataModel_Predicate();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.mDML.DataItem <em>Data Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Data Item</em>'.
   * @see uk.ac.ox.cs.mDML.DataItem
   * @generated
   */
  EClass getDataItem();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.ox.cs.mDML.DataItem#getDataitem <em>Dataitem</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Dataitem</em>'.
   * @see uk.ac.ox.cs.mDML.DataItem#getDataitem()
   * @see #getDataItem()
   * @generated
   */
  EReference getDataItem_Dataitem();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.mDML.Reference <em>Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Reference</em>'.
   * @see uk.ac.ox.cs.mDML.Reference
   * @generated
   */
  EClass getReference();

  /**
   * Returns the meta object for the reference '{@link uk.ac.ox.cs.mDML.Reference#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see uk.ac.ox.cs.mDML.Reference#getType()
   * @see #getReference()
   * @generated
   */
  EReference getReference_Type();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.mDML.RelationSource <em>Relation Source</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Relation Source</em>'.
   * @see uk.ac.ox.cs.mDML.RelationSource
   * @generated
   */
  EClass getRelationSource();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.mDML.RelationDestination <em>Relation Destination</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Relation Destination</em>'.
   * @see uk.ac.ox.cs.mDML.RelationDestination
   * @generated
   */
  EClass getRelationDestination();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.mDML.Relationship <em>Relationship</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Relationship</em>'.
   * @see uk.ac.ox.cs.mDML.Relationship
   * @generated
   */
  EClass getRelationship();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.ox.cs.mDML.Relationship#getSrc <em>Src</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Src</em>'.
   * @see uk.ac.ox.cs.mDML.Relationship#getSrc()
   * @see #getRelationship()
   * @generated
   */
  EReference getRelationship_Src();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.ox.cs.mDML.Relationship#getDest <em>Dest</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Dest</em>'.
   * @see uk.ac.ox.cs.mDML.Relationship#getDest()
   * @see #getRelationship()
   * @generated
   */
  EReference getRelationship_Dest();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.mDML.ExtensionItem <em>Extension Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Extension Item</em>'.
   * @see uk.ac.ox.cs.mDML.ExtensionItem
   * @generated
   */
  EClass getExtensionItem();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.ox.cs.mDML.ExtensionItem#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see uk.ac.ox.cs.mDML.ExtensionItem#getKey()
   * @see #getExtensionItem()
   * @generated
   */
  EAttribute getExtensionItem_Key();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.ox.cs.mDML.ExtensionItem#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see uk.ac.ox.cs.mDML.ExtensionItem#getValue()
   * @see #getExtensionItem()
   * @generated
   */
  EAttribute getExtensionItem_Value();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.mDML.Import <em>Import</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Import</em>'.
   * @see uk.ac.ox.cs.mDML.Import
   * @generated
   */
  EClass getImport();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.ox.cs.mDML.Import#getImportedNamespace <em>Imported Namespace</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Imported Namespace</em>'.
   * @see uk.ac.ox.cs.mDML.Import#getImportedNamespace()
   * @see #getImport()
   * @generated
   */
  EAttribute getImport_ImportedNamespace();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.mDML.DataType <em>Data Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Data Type</em>'.
   * @see uk.ac.ox.cs.mDML.DataType
   * @generated
   */
  EClass getDataType();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.ox.cs.mDML.DataType#getStatus <em>Status</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Status</em>'.
   * @see uk.ac.ox.cs.mDML.DataType#getStatus()
   * @see #getDataType()
   * @generated
   */
  EAttribute getDataType_Status();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.ox.cs.mDML.DataType#getGuid <em>Guid</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Guid</em>'.
   * @see uk.ac.ox.cs.mDML.DataType#getGuid()
   * @see #getDataType()
   * @generated
   */
  EAttribute getDataType_Guid();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.ox.cs.mDML.DataType#getRefines <em>Refines</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Refines</em>'.
   * @see uk.ac.ox.cs.mDML.DataType#getRefines()
   * @see #getDataType()
   * @generated
   */
  EAttribute getDataType_Refines();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.ox.cs.mDML.DataType#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.ox.cs.mDML.DataType#getName()
   * @see #getDataType()
   * @generated
   */
  EAttribute getDataType_Name();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.mDML.EnumeratedType <em>Enumerated Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Enumerated Type</em>'.
   * @see uk.ac.ox.cs.mDML.EnumeratedType
   * @generated
   */
  EClass getEnumeratedType();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.ox.cs.mDML.EnumeratedType#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see uk.ac.ox.cs.mDML.EnumeratedType#getType()
   * @see #getEnumeratedType()
   * @generated
   */
  EReference getEnumeratedType_Type();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.ox.cs.mDML.EnumeratedType#isArray <em>Array</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Array</em>'.
   * @see uk.ac.ox.cs.mDML.EnumeratedType#isArray()
   * @see #getEnumeratedType()
   * @generated
   */
  EAttribute getEnumeratedType_Array();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.ox.cs.mDML.EnumeratedType#getLength <em>Length</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Length</em>'.
   * @see uk.ac.ox.cs.mDML.EnumeratedType#getLength()
   * @see #getEnumeratedType()
   * @generated
   */
  EAttribute getEnumeratedType_Length();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.mDML.ReferenceType <em>Reference Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Reference Type</em>'.
   * @see uk.ac.ox.cs.mDML.ReferenceType
   * @generated
   */
  EClass getReferenceType();

  /**
   * Returns the meta object for the reference '{@link uk.ac.ox.cs.mDML.ReferenceType#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see uk.ac.ox.cs.mDML.ReferenceType#getType()
   * @see #getReferenceType()
   * @generated
   */
  EReference getReferenceType_Type();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.mDML.PrimitiveType <em>Primitive Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Primitive Type</em>'.
   * @see uk.ac.ox.cs.mDML.PrimitiveType
   * @generated
   */
  EClass getPrimitiveType();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.ox.cs.mDML.PrimitiveType#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see uk.ac.ox.cs.mDML.PrimitiveType#getType()
   * @see #getPrimitiveType()
   * @generated
   */
  EReference getPrimitiveType_Type();

  /**
   * Returns the meta object for the reference '{@link uk.ac.ox.cs.mDML.PrimitiveType#getRule <em>Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Rule</em>'.
   * @see uk.ac.ox.cs.mDML.PrimitiveType#getRule()
   * @see #getPrimitiveType()
   * @generated
   */
  EReference getPrimitiveType_Rule();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.mDML.Basic <em>Basic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Basic</em>'.
   * @see uk.ac.ox.cs.mDML.Basic
   * @generated
   */
  EClass getBasic();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.ox.cs.mDML.Basic#getTypename <em>Typename</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Typename</em>'.
   * @see uk.ac.ox.cs.mDML.Basic#getTypename()
   * @see #getBasic()
   * @generated
   */
  EAttribute getBasic_Typename();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.mDML.ContainerElement <em>Container Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Container Element</em>'.
   * @see uk.ac.ox.cs.mDML.ContainerElement
   * @generated
   */
  EClass getContainerElement();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.ox.cs.mDML.ContainerElement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.ox.cs.mDML.ContainerElement#getName()
   * @see #getContainerElement()
   * @generated
   */
  EAttribute getContainerElement_Name();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.mDML.DataClass <em>Data Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Data Class</em>'.
   * @see uk.ac.ox.cs.mDML.DataClass
   * @generated
   */
  EClass getDataClass();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.ox.cs.mDML.DataClass#getStatus <em>Status</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Status</em>'.
   * @see uk.ac.ox.cs.mDML.DataClass#getStatus()
   * @see #getDataClass()
   * @generated
   */
  EAttribute getDataClass_Status();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.ox.cs.mDML.DataClass#getGuid <em>Guid</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Guid</em>'.
   * @see uk.ac.ox.cs.mDML.DataClass#getGuid()
   * @see #getDataClass()
   * @generated
   */
  EAttribute getDataClass_Guid();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.ox.cs.mDML.DataClass#getRefines <em>Refines</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Refines</em>'.
   * @see uk.ac.ox.cs.mDML.DataClass#getRefines()
   * @see #getDataClass()
   * @generated
   */
  EAttribute getDataClass_Refines();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.ox.cs.mDML.DataClass#getDataelements <em>Dataelements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Dataelements</em>'.
   * @see uk.ac.ox.cs.mDML.DataClass#getDataelements()
   * @see #getDataClass()
   * @generated
   */
  EReference getDataClass_Dataelements();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.ox.cs.mDML.DataClass#getExtension <em>Extension</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Extension</em>'.
   * @see uk.ac.ox.cs.mDML.DataClass#getExtension()
   * @see #getDataClass()
   * @generated
   */
  EReference getDataClass_Extension();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.mDML.DataElement <em>Data Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Data Element</em>'.
   * @see uk.ac.ox.cs.mDML.DataElement
   * @generated
   */
  EClass getDataElement();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.ox.cs.mDML.DataElement#getStatus <em>Status</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Status</em>'.
   * @see uk.ac.ox.cs.mDML.DataElement#getStatus()
   * @see #getDataElement()
   * @generated
   */
  EAttribute getDataElement_Status();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.ox.cs.mDML.DataElement#getGuid <em>Guid</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Guid</em>'.
   * @see uk.ac.ox.cs.mDML.DataElement#getGuid()
   * @see #getDataElement()
   * @generated
   */
  EAttribute getDataElement_Guid();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.ox.cs.mDML.DataElement#getRefines <em>Refines</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Refines</em>'.
   * @see uk.ac.ox.cs.mDML.DataElement#getRefines()
   * @see #getDataElement()
   * @generated
   */
  EAttribute getDataElement_Refines();

  /**
   * Returns the meta object for the reference '{@link uk.ac.ox.cs.mDML.DataElement#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see uk.ac.ox.cs.mDML.DataElement#getType()
   * @see #getDataElement()
   * @generated
   */
  EReference getDataElement_Type();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.mDML.Constraint <em>Constraint</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Constraint</em>'.
   * @see uk.ac.ox.cs.mDML.Constraint
   * @generated
   */
  EClass getConstraint();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.ox.cs.mDML.Constraint#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.ox.cs.mDML.Constraint#getName()
   * @see #getConstraint()
   * @generated
   */
  EAttribute getConstraint_Name();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.ox.cs.mDML.Constraint#getSrc <em>Src</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Src</em>'.
   * @see uk.ac.ox.cs.mDML.Constraint#getSrc()
   * @see #getConstraint()
   * @generated
   */
  EReference getConstraint_Src();

  /**
   * Returns the meta object for the reference '{@link uk.ac.ox.cs.mDML.Constraint#getPred <em>Pred</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Pred</em>'.
   * @see uk.ac.ox.cs.mDML.Constraint#getPred()
   * @see #getConstraint()
   * @generated
   */
  EReference getConstraint_Pred();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.ox.cs.mDML.Constraint#getDest <em>Dest</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Dest</em>'.
   * @see uk.ac.ox.cs.mDML.Constraint#getDest()
   * @see #getConstraint()
   * @generated
   */
  EReference getConstraint_Dest();

  /**
   * Returns the meta object for class '{@link uk.ac.ox.cs.mDML.Predicate <em>Predicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Predicate</em>'.
   * @see uk.ac.ox.cs.mDML.Predicate
   * @generated
   */
  EClass getPredicate();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.ox.cs.mDML.Predicate#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.ox.cs.mDML.Predicate#getName()
   * @see #getPredicate()
   * @generated
   */
  EAttribute getPredicate_Name();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.ox.cs.mDML.Predicate#getPredicate <em>Predicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Predicate</em>'.
   * @see uk.ac.ox.cs.mDML.Predicate#getPredicate()
   * @see #getPredicate()
   * @generated
   */
  EAttribute getPredicate_Predicate();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MDMLFactory getMDMLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.mDML.impl.DomainRegistryImpl <em>Domain Registry</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.mDML.impl.DomainRegistryImpl
     * @see uk.ac.ox.cs.mDML.impl.MDMLPackageImpl#getDomainRegistry()
     * @generated
     */
    EClass DOMAIN_REGISTRY = eINSTANCE.getDomainRegistry();

    /**
     * The meta object literal for the '<em><b>Registered Items</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOMAIN_REGISTRY__REGISTERED_ITEMS = eINSTANCE.getDomainRegistry_RegisteredItems();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.mDML.impl.DataModelImpl <em>Data Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.mDML.impl.DataModelImpl
     * @see uk.ac.ox.cs.mDML.impl.MDMLPackageImpl#getDataModel()
     * @generated
     */
    EClass DATA_MODEL = eINSTANCE.getDataModel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA_MODEL__NAME = eINSTANCE.getDataModel_Name();

    /**
     * The meta object literal for the '<em><b>Status</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA_MODEL__STATUS = eINSTANCE.getDataModel_Status();

    /**
     * The meta object literal for the '<em><b>Guid</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA_MODEL__GUID = eINSTANCE.getDataModel_Guid();

    /**
     * The meta object literal for the '<em><b>Refines</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA_MODEL__REFINES = eINSTANCE.getDataModel_Refines();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DATA_MODEL__ELEMENTS = eINSTANCE.getDataModel_Elements();

    /**
     * The meta object literal for the '<em><b>Relations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DATA_MODEL__RELATIONS = eINSTANCE.getDataModel_Relations();

    /**
     * The meta object literal for the '<em><b>Constraint</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DATA_MODEL__CONSTRAINT = eINSTANCE.getDataModel_Constraint();

    /**
     * The meta object literal for the '<em><b>Predicate</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DATA_MODEL__PREDICATE = eINSTANCE.getDataModel_Predicate();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.mDML.impl.DataItemImpl <em>Data Item</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.mDML.impl.DataItemImpl
     * @see uk.ac.ox.cs.mDML.impl.MDMLPackageImpl#getDataItem()
     * @generated
     */
    EClass DATA_ITEM = eINSTANCE.getDataItem();

    /**
     * The meta object literal for the '<em><b>Dataitem</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DATA_ITEM__DATAITEM = eINSTANCE.getDataItem_Dataitem();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.mDML.impl.ReferenceImpl <em>Reference</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.mDML.impl.ReferenceImpl
     * @see uk.ac.ox.cs.mDML.impl.MDMLPackageImpl#getReference()
     * @generated
     */
    EClass REFERENCE = eINSTANCE.getReference();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REFERENCE__TYPE = eINSTANCE.getReference_Type();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.mDML.impl.RelationSourceImpl <em>Relation Source</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.mDML.impl.RelationSourceImpl
     * @see uk.ac.ox.cs.mDML.impl.MDMLPackageImpl#getRelationSource()
     * @generated
     */
    EClass RELATION_SOURCE = eINSTANCE.getRelationSource();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.mDML.impl.RelationDestinationImpl <em>Relation Destination</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.mDML.impl.RelationDestinationImpl
     * @see uk.ac.ox.cs.mDML.impl.MDMLPackageImpl#getRelationDestination()
     * @generated
     */
    EClass RELATION_DESTINATION = eINSTANCE.getRelationDestination();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.mDML.impl.RelationshipImpl <em>Relationship</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.mDML.impl.RelationshipImpl
     * @see uk.ac.ox.cs.mDML.impl.MDMLPackageImpl#getRelationship()
     * @generated
     */
    EClass RELATIONSHIP = eINSTANCE.getRelationship();

    /**
     * The meta object literal for the '<em><b>Src</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATIONSHIP__SRC = eINSTANCE.getRelationship_Src();

    /**
     * The meta object literal for the '<em><b>Dest</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATIONSHIP__DEST = eINSTANCE.getRelationship_Dest();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.mDML.impl.ExtensionItemImpl <em>Extension Item</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.mDML.impl.ExtensionItemImpl
     * @see uk.ac.ox.cs.mDML.impl.MDMLPackageImpl#getExtensionItem()
     * @generated
     */
    EClass EXTENSION_ITEM = eINSTANCE.getExtensionItem();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXTENSION_ITEM__KEY = eINSTANCE.getExtensionItem_Key();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXTENSION_ITEM__VALUE = eINSTANCE.getExtensionItem_Value();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.mDML.impl.ImportImpl <em>Import</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.mDML.impl.ImportImpl
     * @see uk.ac.ox.cs.mDML.impl.MDMLPackageImpl#getImport()
     * @generated
     */
    EClass IMPORT = eINSTANCE.getImport();

    /**
     * The meta object literal for the '<em><b>Imported Namespace</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMPORT__IMPORTED_NAMESPACE = eINSTANCE.getImport_ImportedNamespace();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.mDML.impl.DataTypeImpl <em>Data Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.mDML.impl.DataTypeImpl
     * @see uk.ac.ox.cs.mDML.impl.MDMLPackageImpl#getDataType()
     * @generated
     */
    EClass DATA_TYPE = eINSTANCE.getDataType();

    /**
     * The meta object literal for the '<em><b>Status</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA_TYPE__STATUS = eINSTANCE.getDataType_Status();

    /**
     * The meta object literal for the '<em><b>Guid</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA_TYPE__GUID = eINSTANCE.getDataType_Guid();

    /**
     * The meta object literal for the '<em><b>Refines</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA_TYPE__REFINES = eINSTANCE.getDataType_Refines();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA_TYPE__NAME = eINSTANCE.getDataType_Name();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.mDML.impl.EnumeratedTypeImpl <em>Enumerated Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.mDML.impl.EnumeratedTypeImpl
     * @see uk.ac.ox.cs.mDML.impl.MDMLPackageImpl#getEnumeratedType()
     * @generated
     */
    EClass ENUMERATED_TYPE = eINSTANCE.getEnumeratedType();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENUMERATED_TYPE__TYPE = eINSTANCE.getEnumeratedType_Type();

    /**
     * The meta object literal for the '<em><b>Array</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENUMERATED_TYPE__ARRAY = eINSTANCE.getEnumeratedType_Array();

    /**
     * The meta object literal for the '<em><b>Length</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENUMERATED_TYPE__LENGTH = eINSTANCE.getEnumeratedType_Length();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.mDML.impl.ReferenceTypeImpl <em>Reference Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.mDML.impl.ReferenceTypeImpl
     * @see uk.ac.ox.cs.mDML.impl.MDMLPackageImpl#getReferenceType()
     * @generated
     */
    EClass REFERENCE_TYPE = eINSTANCE.getReferenceType();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REFERENCE_TYPE__TYPE = eINSTANCE.getReferenceType_Type();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.mDML.impl.PrimitiveTypeImpl <em>Primitive Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.mDML.impl.PrimitiveTypeImpl
     * @see uk.ac.ox.cs.mDML.impl.MDMLPackageImpl#getPrimitiveType()
     * @generated
     */
    EClass PRIMITIVE_TYPE = eINSTANCE.getPrimitiveType();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRIMITIVE_TYPE__TYPE = eINSTANCE.getPrimitiveType_Type();

    /**
     * The meta object literal for the '<em><b>Rule</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRIMITIVE_TYPE__RULE = eINSTANCE.getPrimitiveType_Rule();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.mDML.impl.BasicImpl <em>Basic</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.mDML.impl.BasicImpl
     * @see uk.ac.ox.cs.mDML.impl.MDMLPackageImpl#getBasic()
     * @generated
     */
    EClass BASIC = eINSTANCE.getBasic();

    /**
     * The meta object literal for the '<em><b>Typename</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BASIC__TYPENAME = eINSTANCE.getBasic_Typename();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.mDML.impl.ContainerElementImpl <em>Container Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.mDML.impl.ContainerElementImpl
     * @see uk.ac.ox.cs.mDML.impl.MDMLPackageImpl#getContainerElement()
     * @generated
     */
    EClass CONTAINER_ELEMENT = eINSTANCE.getContainerElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTAINER_ELEMENT__NAME = eINSTANCE.getContainerElement_Name();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.mDML.impl.DataClassImpl <em>Data Class</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.mDML.impl.DataClassImpl
     * @see uk.ac.ox.cs.mDML.impl.MDMLPackageImpl#getDataClass()
     * @generated
     */
    EClass DATA_CLASS = eINSTANCE.getDataClass();

    /**
     * The meta object literal for the '<em><b>Status</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA_CLASS__STATUS = eINSTANCE.getDataClass_Status();

    /**
     * The meta object literal for the '<em><b>Guid</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA_CLASS__GUID = eINSTANCE.getDataClass_Guid();

    /**
     * The meta object literal for the '<em><b>Refines</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA_CLASS__REFINES = eINSTANCE.getDataClass_Refines();

    /**
     * The meta object literal for the '<em><b>Dataelements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DATA_CLASS__DATAELEMENTS = eINSTANCE.getDataClass_Dataelements();

    /**
     * The meta object literal for the '<em><b>Extension</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DATA_CLASS__EXTENSION = eINSTANCE.getDataClass_Extension();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.mDML.impl.DataElementImpl <em>Data Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.mDML.impl.DataElementImpl
     * @see uk.ac.ox.cs.mDML.impl.MDMLPackageImpl#getDataElement()
     * @generated
     */
    EClass DATA_ELEMENT = eINSTANCE.getDataElement();

    /**
     * The meta object literal for the '<em><b>Status</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA_ELEMENT__STATUS = eINSTANCE.getDataElement_Status();

    /**
     * The meta object literal for the '<em><b>Guid</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA_ELEMENT__GUID = eINSTANCE.getDataElement_Guid();

    /**
     * The meta object literal for the '<em><b>Refines</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA_ELEMENT__REFINES = eINSTANCE.getDataElement_Refines();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DATA_ELEMENT__TYPE = eINSTANCE.getDataElement_Type();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.mDML.impl.ConstraintImpl <em>Constraint</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.mDML.impl.ConstraintImpl
     * @see uk.ac.ox.cs.mDML.impl.MDMLPackageImpl#getConstraint()
     * @generated
     */
    EClass CONSTRAINT = eINSTANCE.getConstraint();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONSTRAINT__NAME = eINSTANCE.getConstraint_Name();

    /**
     * The meta object literal for the '<em><b>Src</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONSTRAINT__SRC = eINSTANCE.getConstraint_Src();

    /**
     * The meta object literal for the '<em><b>Pred</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONSTRAINT__PRED = eINSTANCE.getConstraint_Pred();

    /**
     * The meta object literal for the '<em><b>Dest</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONSTRAINT__DEST = eINSTANCE.getConstraint_Dest();

    /**
     * The meta object literal for the '{@link uk.ac.ox.cs.mDML.impl.PredicateImpl <em>Predicate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.ox.cs.mDML.impl.PredicateImpl
     * @see uk.ac.ox.cs.mDML.impl.MDMLPackageImpl#getPredicate()
     * @generated
     */
    EClass PREDICATE = eINSTANCE.getPredicate();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PREDICATE__NAME = eINSTANCE.getPredicate_Name();

    /**
     * The meta object literal for the '<em><b>Predicate</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PREDICATE__PREDICATE = eINSTANCE.getPredicate_Predicate();

  }

} //MDMLPackage
