/**
 * generated by Xtext 2.12.0
 */
package uk.ac.ox.cs.mDML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Reference Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.ox.cs.mDML.ReferenceType#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see uk.ac.ox.cs.mDML.MDMLPackage#getReferenceType()
 * @model
 * @generated
 */
public interface ReferenceType extends DataType
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(DataClass)
   * @see uk.ac.ox.cs.mDML.MDMLPackage#getReferenceType_Type()
   * @model
   * @generated
   */
  DataClass getType();

  /**
   * Sets the value of the '{@link uk.ac.ox.cs.mDML.ReferenceType#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(DataClass value);

} // ReferenceType
