/**
 * generated by Xtext 2.12.0
 */
package uk.ac.ox.cs.mDML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Relation Destination</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uk.ac.ox.cs.mDML.MDMLPackage#getRelationDestination()
 * @model
 * @generated
 */
public interface RelationDestination extends EObject
{
} // RelationDestination
