/**
 * generated by Xtext 2.12.0
 */
package uk.ac.ox.cs.mDML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Relation Source</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uk.ac.ox.cs.mDML.MDMLPackage#getRelationSource()
 * @model
 * @generated
 */
public interface RelationSource extends EObject
{
} // RelationSource
