/**
 * generated by Xtext 2.12.0
 */
package uk.ac.ox.cs.mDML.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import uk.ac.ox.cs.mDML.DataModel;
import uk.ac.ox.cs.mDML.DomainRegistry;
import uk.ac.ox.cs.mDML.MDMLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Domain Registry</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.ox.cs.mDML.impl.DomainRegistryImpl#getRegisteredItems <em>Registered Items</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DomainRegistryImpl extends MinimalEObjectImpl.Container implements DomainRegistry
{
  /**
   * The cached value of the '{@link #getRegisteredItems() <em>Registered Items</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRegisteredItems()
   * @generated
   * @ordered
   */
  protected EList<DataModel> registeredItems;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DomainRegistryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MDMLPackage.Literals.DOMAIN_REGISTRY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<DataModel> getRegisteredItems()
  {
    if (registeredItems == null)
    {
      registeredItems = new EObjectContainmentEList<DataModel>(DataModel.class, this, MDMLPackage.DOMAIN_REGISTRY__REGISTERED_ITEMS);
    }
    return registeredItems;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MDMLPackage.DOMAIN_REGISTRY__REGISTERED_ITEMS:
        return ((InternalEList<?>)getRegisteredItems()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MDMLPackage.DOMAIN_REGISTRY__REGISTERED_ITEMS:
        return getRegisteredItems();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MDMLPackage.DOMAIN_REGISTRY__REGISTERED_ITEMS:
        getRegisteredItems().clear();
        getRegisteredItems().addAll((Collection<? extends DataModel>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MDMLPackage.DOMAIN_REGISTRY__REGISTERED_ITEMS:
        getRegisteredItems().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MDMLPackage.DOMAIN_REGISTRY__REGISTERED_ITEMS:
        return registeredItems != null && !registeredItems.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //DomainRegistryImpl
