/**
 * generated by Xtext 2.12.0
 */
package uk.ac.ox.cs.mDML.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import uk.ac.ox.cs.mDML.MDMLPackage;
import uk.ac.ox.cs.mDML.RelationDestination;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Relation Destination</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RelationDestinationImpl extends MinimalEObjectImpl.Container implements RelationDestination
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RelationDestinationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MDMLPackage.Literals.RELATION_DESTINATION;
  }

} //RelationDestinationImpl
