/**
 * generated by Xtext 2.12.0
 */
package uk.ac.ox.cs.mDML.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import uk.ac.ox.cs.mDML.MDMLPackage;
import uk.ac.ox.cs.mDML.RelationSource;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Relation Source</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RelationSourceImpl extends MinimalEObjectImpl.Container implements RelationSource
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RelationSourceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MDMLPackage.Literals.RELATION_SOURCE;
  }

} //RelationSourceImpl
