/*
 * generated by Xtext 2.12.0
 */
package uk.ac.ox.cs.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import uk.ac.ox.cs.parser.antlr.internal.InternalMDMLParser;
import uk.ac.ox.cs.services.MDMLGrammarAccess;

public class MDMLParser extends AbstractAntlrParser {

	@Inject
	private MDMLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMDMLParser createParser(XtextTokenStream stream) {
		return new InternalMDMLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "DomainRegistry";
	}

	public MDMLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MDMLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
