/**
 * generated by Xtext 2.12.0
 */
package uk.ac.ox.cs.ui.contentassist;

import uk.ac.ox.cs.ui.contentassist.AbstractMDMLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class MDMLProposalProvider extends AbstractMDMLProposalProvider {
}
