/**
 * generated by Xtext 2.12.0
 */
package uk.ac.ox.cs;

import uk.ac.ox.cs.AbstractMDMLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MDMLRuntimeModule extends AbstractMDMLRuntimeModule {
}
