/**
 * generated by Xtext 2.12.0
 */
package uk.ac.ox.cs;

import uk.ac.ox.cs.MDMLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class MDMLStandaloneSetup extends MDMLStandaloneSetupGenerated {
  public static void doSetup() {
    new MDMLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
